#############################################################################
# Makefile for building: PDEsolver.app/Contents/MacOS/PDEsolver
# Generated by qmake (2.01a) (Qt 4.8.5) on: Mon Apr 14 14:07:31 2014
# Project:  PDEsolver.pro
# Template: app
# Command: /usr/bin/qmake -o PDEsolver.xcodeproj/project.pbxproj PDEsolver.pro
#############################################################################

MOC       = /Developer/Tools/Qt/moc
UIC       = /Developer/Tools/Qt/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-xcode -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -IApplication -IFieldsDefinition -IGlobalFunctions -ISimulation -ISolvers/TwoDimensional -ISolvers/TwoDimensional/FluxSolvers -IInitialCondition -ISolvers/OneDimensional -ISolvers/OneDimensional/FluxSolvers -IApplication/QCustomPlot -I. -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers -F/Library/Frameworks
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compilers: ./moc_PlottingMainWindow.cpp ./moc_SimulationMainWindow.cpp ./moc_SimulationMainWindow1D.cpp\
	 ./moc_SimulationMainWindow2D.cpp ./moc_qcustomplot.cpp
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_PlottingMainWindow.cpp moc_SimulationMainWindow.cpp moc_SimulationMainWindow1D.cpp moc_SimulationMainWindow2D.cpp moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_PlottingMainWindow.cpp moc_SimulationMainWindow.cpp moc_SimulationMainWindow1D.cpp moc_SimulationMainWindow2D.cpp moc_qcustomplot.cpp
moc_PlottingMainWindow.cpp: Application/QCustomPlot/qcustomplot.h \
		Solvers/OneDimensional/MainSolverClass.h \
		constants.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorClass.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassMUSCLScheme.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassLinearReconstructionScheme.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorPiecewiseParabolicReconstructionScheme.h \
		Solvers/OneDimensional/RK4Scheme.h \
		Solvers/OneDimensional/MacCormackScheme.h \
		Solvers/OneDimensional/ForwardEulerScheme.h \
		Solvers/OneDimensional/LaxFriedrichsScheme.h \
		Solvers/OneDimensional/KurganovTadmor2000Scheme.h \
		Solvers/OneDimensional/RK4KurganovTadmor2000Scheme.h \
		Solvers/OneDimensional/KurganovTadmor2ndOrder2000Scheme.h \
		FieldsDefinition/Field1DClass.h \
		InitialCondition/InitialConditionClass.h \
		InitialCondition/InitialConditionClass_Sin.h \
		InitialCondition/InitialConditionClass_Step.h \
		InitialCondition/InitialConditionClass_RndNoise.h \
		Application/PlottingMainWindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Application/PlottingMainWindow.h -o moc_PlottingMainWindow.cpp

moc_SimulationMainWindow.cpp: Application/SimulationMainWindow2D.h \
		FieldsDefinition/Field2DClass.h \
		GlobalFunctions/saveDataIntoFile.h \
		Simulation/Simulation2DClass.h \
		GlobalFunctions/saveImageIntoFile.h \
		Solvers/TwoDimensional/MainSolverClass2D.h \
		constants.h \
		Solvers/TwoDimensional/FluxSolvers/FluxCalculatorClass2D.h \
		Solvers/TwoDimensional/FluxSolvers/FluxCalculatorClassLinearReconstructionScheme2D.h \
		Solvers/TwoDimensional/RK4Scheme2D.h \
		Solvers/TwoDimensional/ForwardEulerScheme2D.h \
		Solvers/TwoDimensional/LaxFriedrichsScheme2D.h \
		Application/SimulationMainWindow1D.h \
		FieldsDefinition/Field1DClass.h \
		InitialCondition/InitialConditionClass.h \
		InitialCondition/InitialConditionClass_Sin.h \
		InitialCondition/InitialConditionClass_Step.h \
		InitialCondition/InitialConditionClass_RndNoise.h \
		Simulation/Simulation1DClass.h \
		Solvers/OneDimensional/MainSolverClass.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorClass.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassMUSCLScheme.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassLinearReconstructionScheme.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorPiecewiseParabolicReconstructionScheme.h \
		Solvers/OneDimensional/RK4Scheme.h \
		Solvers/OneDimensional/MacCormackScheme.h \
		Solvers/OneDimensional/ForwardEulerScheme.h \
		Solvers/OneDimensional/LaxFriedrichsScheme.h \
		Solvers/OneDimensional/KurganovTadmor2000Scheme.h \
		Solvers/OneDimensional/RK4KurganovTadmor2000Scheme.h \
		Solvers/OneDimensional/KurganovTadmor2ndOrder2000Scheme.h \
		Application/QCustomPlot/qcustomplot.h \
		Application/PlottingMainWindow.h \
		Application/SimulationMainWindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Application/SimulationMainWindow.h -o moc_SimulationMainWindow.cpp

moc_SimulationMainWindow1D.cpp: FieldsDefinition/Field1DClass.h \
		InitialCondition/InitialConditionClass.h \
		InitialCondition/InitialConditionClass_Sin.h \
		InitialCondition/InitialConditionClass_Step.h \
		InitialCondition/InitialConditionClass_RndNoise.h \
		Simulation/Simulation1DClass.h \
		GlobalFunctions/saveDataIntoFile.h \
		Solvers/OneDimensional/MainSolverClass.h \
		constants.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorClass.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassMUSCLScheme.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorClassLinearReconstructionScheme.h \
		Solvers/OneDimensional/FluxSolvers/FluxCalculatorPiecewiseParabolicReconstructionScheme.h \
		Solvers/OneDimensional/RK4Scheme.h \
		Solvers/OneDimensional/MacCormackScheme.h \
		Solvers/OneDimensional/ForwardEulerScheme.h \
		Solvers/OneDimensional/LaxFriedrichsScheme.h \
		Solvers/OneDimensional/KurganovTadmor2000Scheme.h \
		Solvers/OneDimensional/RK4KurganovTadmor2000Scheme.h \
		Solvers/OneDimensional/KurganovTadmor2ndOrder2000Scheme.h \
		Application/QCustomPlot/qcustomplot.h \
		Application/PlottingMainWindow.h \
		Application/SimulationMainWindow1D.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Application/SimulationMainWindow1D.h -o moc_SimulationMainWindow1D.cpp

moc_SimulationMainWindow2D.cpp: FieldsDefinition/Field2DClass.h \
		GlobalFunctions/saveDataIntoFile.h \
		Simulation/Simulation2DClass.h \
		GlobalFunctions/saveImageIntoFile.h \
		Solvers/TwoDimensional/MainSolverClass2D.h \
		constants.h \
		Solvers/TwoDimensional/FluxSolvers/FluxCalculatorClass2D.h \
		Solvers/TwoDimensional/FluxSolvers/FluxCalculatorClassLinearReconstructionScheme2D.h \
		Solvers/TwoDimensional/RK4Scheme2D.h \
		Solvers/TwoDimensional/ForwardEulerScheme2D.h \
		Solvers/TwoDimensional/LaxFriedrichsScheme2D.h \
		Application/SimulationMainWindow2D.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Application/SimulationMainWindow2D.h -o moc_SimulationMainWindow2D.cpp

moc_qcustomplot.cpp: Application/QCustomPlot/qcustomplot.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Application/QCustomPlot/qcustomplot.h -o moc_qcustomplot.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

